sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_278b7835c937_key -iv $encrypted_278b7835c937_iv -in google-cloud-vision-key.json.enc -out google-cloud-vision-key.json -d
  - openssl aes-256-cbc -K $encrypted_278b7835c937_key -iv $encrypted_278b7835c937_iv -in storytime-key.json.enc -out storytime-key.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file storytime-key.json
  - gcloud config set project storytime-238122
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials storytime-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
