version: '3'
services:
  backend:
    network_mode: 'host'
    build:
      dockerfile: Dockerfile
      context: ./backend
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
  nginx:
    restart: always
    ports:
      - '80:80'
    build:
      dockerfile: Dockerfile
      context: ./nginx
